version: "3.8"

services:
    postgres:
        image: postgres:15-alpine
        container_name: geostream-db
        environment:
            POSTGRES_USER: geo
            POSTGRES_PASSWORD: geostream
            POSTGRES_DB: geostream
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        container_name: geostream-redis
        ports:
            - "6379:6379"

    kafka:
        image: confluentinc/cp-kafka:7.4.0
        container_name: geostream-kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
            KAFKA_JMX_PORT: 9101
            KAFKA_JMX_HOSTNAME: localhost
            KAFKA_PROCESS_ROLES: "broker,controller"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
            KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
            KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
            KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
            KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: geostream-kafka-ui
        ports:
            - "8085:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

    # --- GO BACKEND ---
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: geostream-backend
        depends_on:
            - postgres
            - kafka
            - redis
        ports:
            - "8080:8080"
            - "50051:50051" # gRPC port
        environment:
            DB_HOST: postgres
            KAFKA_BROKERS: kafka:29092
            REDIS_HOST: redis:6379

volumes:
    postgres_data:
